from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1452, 862)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ArtificialintelligenceUi = QtWidgets.QLabel(self.centralwidget)
        self.ArtificialintelligenceUi.setGeometry(QtCore.QRect(-110, -130, 1711, 1081))
        self.ArtificialintelligenceUi.setText("")
        self.ArtificialintelligenceUi.setPixmap(QtGui.QPixmap("../Pixel/Gifs/23.jpg"))
        self.ArtificialintelligenceUi.setScaledContents(True)
        self.ArtificialintelligenceUi.setObjectName("ArtificialintelligenceUi")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(534, 540, 411, 291))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Pixel/Gifs/1.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(504, 119, 421, 451))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../Pixel/Gifs/crop6.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 401, 101))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../Pixel/Gifs/20.gif"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1140, 250, 301, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../Pixel/Gifs/14.gif"))
        self.label_5.setScaledContents(False)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 560, 211, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../Pixel/Gifs/11.gif"))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1130, 530, 311, 71))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../Pixel/Gifs/12.gif"))
        self.label_7.setScaledContents(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 670, 461, 41))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../Pixel/Gifs/4.gif"))
        self.label_8.setScaledContents(False)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(970, 670, 481, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../Pixel/Gifs/4.gif"))
        self.label_9.setScaledContents(False)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1090, 5, 361, 221))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("../Pixel/Gifs/10.gif"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 360, 331, 181))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../Pixel/Gifs/7.gif"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(4, 145, 481, 181))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("../Pixel/Gifs/crop25.gif"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1170, 760, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1270, 760, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(560, 10, 321, 91))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("../Pixel/Gifs/26.gif"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(630, 50, 301, 71))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;")
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.pushButton_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
